source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'lolAPIWrapper_Example', :exclusive => true do
  pod "lolAPIWrapper", :path => "../"
end

target 'lolAPIWrapper_Tests', :exclusive => true do
  pod "lolAPIWrapper", :path => "../"

  
end
